Repository Teradata/vantage-ui-platform, pull requests merged in 2020-05, with the labels that each got.

#96 feat: add segmentation icon
  src/docs-ui/app/mat-components/mat-components.component.html
  src/lib/theme/icons/teradata-icons.svg
Labels: ready for merge

#93 feat(app-switcher): some styling adjustments
  src/lib/account-profile/account-profile-menu/account-profile-menu.component.scss
  src/lib/app-switcher/_app-switcher-theme.scss
  src/lib/app-switcher/app-switcher-menu/app-switcher-menu.component.html
  src/lib/app-switcher/app-switcher-menu/app-switcher-menu.component.scss
  src/lib/theme/_overrides.scss
Labels: ready for merge

#100 feat: add disconnect icon
  src/docs-ui/app/mat-components/mat-components.component.html
  src/lib/theme/icons/teradata-icons.svg
Labels: ready for review

#55 feat(connection-service): support multiple connections
  src/docs-ui/app/demos/demos.component.html
  src/docs-ui/app/demos/demos.component.ts
  src/lib/sqle/connection.service.ts
  src/lib/sqle/credentials-dialog/credentials-dialog.component.spec.ts
  src/lib/sqle/credentials-dialog/credentials-dialog.component.ts
  src/lib/sqle/spooled-query.service.ts
Labels: in progress

#101 fix(connection-service): namespace stringify func
  src/lib/sqle/connection.service.ts
Labels: ready for review
