Repository Teradata/vantage-ui-platform, pull requests merged in 2020-03, with the labels that each got.

#60 feat(sqle): add spooled query service
  src/assets/i18n/en.json
  src/lib/sqle/index.ts
  src/lib/sqle/spooled-query.service.ts
  src/lib/sqle/sqle.module.ts
Labels: enhancement

#58 Feat/svg icon set
  angular.json
  scripts/build-release
  src/docs-ui/app/app.component.ts
  src/docs-ui/app/mat-components/mat-components.component.html
  src/docs-ui/app/mat-components/mat-components.component.scss
  src/lib/theme/icons/teradata-icons.svg
Labels: enhancement, ready for review

#63 fix(query-service): use tdhttp service
  src/lib/sqle/query.service.ts
Labels: ready for review

#64 fix(connection-service): export read method
  src/lib/sqle/connection.service.ts
Labels: ready for review

#70 feat(app-switcher): adding app switcher component
  angular.json
  karma.conf.js
  src/assets/i18n/en.json
  src/docs-ui/app/app.component.html
  src/docs-ui/app/app.component.ts
  src/docs-ui/app/app.module.ts
  src/lib/app-switcher/_app-switcher-theme.scss
  src/lib/app-switcher/app-switcher.component.html
  src/lib/app-switcher/app-switcher.component.scss
  src/lib/app-switcher/app-switcher.component.spec.ts
  src/lib/app-switcher/app-switcher.component.ts
  src/lib/app-switcher/app-switcher.module.ts
  src/lib/app-switcher/index.ts
  src/lib/app-switcher/public_api.ts
  src/lib/system/system.service.spec.ts
  src/lib/theme/_overrides.scss
  src/lib/theme/icons/teradata-logo.svg
Labels: ready for review

#80 feat: make icons respond to user theme selection
  src/lib/theme/_overrides.scss
  src/lib/theme/icons/teradata-icons.svg
Labels: ready for review
